Menu component
QiTASC/hatchinq pull request #2
Opened 2019-08-23 12:30 UTC by vbalan92

2019-08-27 07:48 UTC, Dzhyrma requested changes

2019-08-27 07:48 UTC, Dzhyrma commented on elm.json
>          "Hatchinq.List",
You need also to bumb a version

2019-08-27 07:48 UTC, Dzhyrma commented on src/Hatchinq/Divider.elm
> +    , height : Length
these configurations shouldn't be here. There are already a part of the Attribute

2019-08-27 07:54 UTC, vneacsu commented on src/Hatchinq/Menu.elm
> +        -- TODO min width?
yes, provide a min with a reasonable default

2019-08-28 09:03 UTC, vneacsu commented on src/Hatchinq/Util.elm
> +onClickPropagation : Bool -> msg -> Element.Attribute msg
`onClickPropagation True` reads a bit confusing. I would simply drop the parameter and name it explicitly `onClickWithoutPropagation` or something similar. This function we anyways use only like that. For all other cases, there is the plain `onClick` event.

2019-08-28 09:03 UTC, vneacsu commented on src/Hatchinq/Menu.elm
> +        Browser.Events.onMouseDown (outsideTarget "menu"
indentation looks a bit funny here. You should use the `elm-format` tool which takes care of the alignment by its own.

2019-08-28 09:23 UTC, dejanas commented on src/Hatchinq/Util.elm
> +onClickPropagation : Bool -> msg -> Element.Attribute msg
I had first set it like you said but it is also used in IconButton where you can pass the propagation flag as well.

2019-08-28 09:26 UTC, vneacsu commented on src/Hatchinq/Util.elm
> +onClickPropagation : Bool -> msg -> Element.Attribute msg
Then I would still name it `onClickWithoutPropagation True`. sounds a bit more intuitive I would say :)

2019-08-28 09:53 UTC, dejanas commented on src/Hatchinq/Util.elm
> +onClickPropagation : Bool -> msg -> Element.Attribute msg
Agreed :)

2019-08-28 10:53 UTC, vneacsu approved these changes

2019-08-29 07:49 UTC, merged

2019-08-29 07:49 UTC, vneacsu approved these changes